/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: ComponentInterface.VM
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/ComponentInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.ilm.algorithm;

import com.splwg.base.api.BusinessComponent;
import com.splwg.base.domain.ilm.genericalgorithm.ILMEligibilitySpot; 

/**
  * Interface for the cmTransactionsILMAlgoComp component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public interface CmTransactionsILMAlgoComp extends BusinessComponent
                 , ILMEligibilitySpot 
                  {

    /**
      * 
      */
     com.splwg.shared.logging.Logger logger = com.splwg.cm.domain.wp.ilm.algorithm.CmTransactionsILMAlgoComp_Impl.logger;


    /**
      * 
      */
     
     void invoke() ;

    /**
      * 
      */
     
     void setBusinessEntity(com.splwg.base.api.BusinessEntity arg0) ;

    /**
      * 
      */
     
     void setCutOffDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setMaintenanceObject(com.splwg.base.domain.common.maintenanceObject.MaintenanceObject arg0) ;

}
