/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: Interface.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/Interface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */





package com.splwg.cm.domain.wp.ilm;



import com.splwg.base.api.Property;
import com.splwg.base.support.changehandlers.PropertyHolder;
import com.splwg.base.support.api.SinglePropertyStaticMetadata;

import com.splwg.base.api.changehandling.*;

import com.splwg.base.api.SimpleKeyedBusinessEntity;

import com.splwg.base.api.SessionManagedEntity;




/**
  * Interface to CmAdjustmentStaging
  *
  * @author Generated by splDev.artifactGenerator
  */
public interface CmAdjustmentStaging 
   extends SimpleKeyedBusinessEntity<CmAdjustmentStaging> , SessionManagedEntity 
{


    /* the prime key */
    /**
      * Get the id property
      *
      * @return the id
      */
    public com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_Id getId();


    /* simple persistent fields */
    /**
      * Get the accountNumber property
      *
      * @return accountNumber
      */
    public java.lang.String getAccountNumber();
    /**
      * Get the adjustmentCategory property
      *
      * @return adjustmentCategory
      */
    public java.lang.String getAdjustmentCategory();
    /**
      * Get the adjustmentStagingControlID property
      *
      * @return adjustmentStagingControlID
      */
    public java.math.BigInteger getAdjustmentStagingControlID();
    /**
      * Get the status property
      *
      * @return status
      */
    public java.lang.String getStatus();
    /**
      * Get the division property
      *
      * @return division
      */
    public java.lang.String getDivision();
    /**
      * Get the errorInfo property
      *
      * @return errorInfo
      */
    public java.lang.String getErrorInfo();
    /**
      * Get the eventId property
      *
      * @return eventId
      */
    public java.lang.String getEventId();
    /**
      * Get the isEligibleForArchiving property
      *
      * @return isEligibleForArchiving
      */
    public com.splwg.base.api.datatypes.Bool getIsEligibleForArchiving();
    /**
      * Get the ilmDate property
      *
      * @return ilmDate
      */
    public com.splwg.base.api.datatypes.Date getIlmDate();
    /**
      * Get the messageCategory property
      *
      * @return messageCategory
      */
    public java.math.BigInteger getMessageCategory();
    /**
      * Get the messageNumber property
      *
      * @return messageNumber
      */
    public java.math.BigInteger getMessageNumber();
    /**
      * Get the saType property
      *
      * @return saType
      */
    public java.lang.String getSaType();
    /**
      * Get the statusDateTime property
      *
      * @return statusDateTime
      */
    public com.splwg.base.api.datatypes.DateTime getStatusDateTime();
    /**
      * Get the uploadDateTime property
      *
      * @return uploadDateTime
      */
    public com.splwg.base.api.datatypes.DateTime getUploadDateTime();

    /* FK properties */

    /* optional FK properties */

    /* Collection accessors */

    /**
      * Get the Data transfer object with this business entity's values
      *
      * @return a Data transfer object based upon this entity
      */
    @Override
    public com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_DTO getDTO();



   
   /**
    * The properties of CmAdjustmentStaging
    *
    */
    public static EntityProperties properties = new EntityProperties();
    
   /**
    * The {@link PropertyHolder} class containing the entities properties
    *
    */
    public static class EntityProperties extends PropertyHolder<com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging> {
    
        //~ Constructors -------------------------------------------------------------------------------------
        
        public EntityProperties(Property<com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging> referencingProperty) {
            super(referencingProperty);
        }

        private EntityProperties() {
            super(null);
        }

        /**
         * @returns Return the entity name
         */
        @Override
        public String getEntityName() {
            return "cmAdjustmentStaging";
        }
            
        @Override    
        public final Property[] getAllProperties(){
            return ALL_PROPERTIES.clone();
        }
    
        /** The accountNumber property */
        public final StringProperty accountNumber
            = new StringProperty(new SinglePropertyStaticMetadata(this, "accountNumber", "CM_ADJ_STG                    ", "ACCT_NBR                      ", false, 30, 0));
        /** The adjustmentCategory property */
        public final StringProperty adjustmentCategory
            = new StringProperty(new SinglePropertyStaticMetadata(this, "adjustmentCategory", "CM_ADJ_STG                    ", "ADJ_CAT_CD                    ", false, 12, 0));
        /** The adjustmentStagingControlID property */
        public final IntegerProperty adjustmentStagingControlID
            = new IntegerProperty(new SinglePropertyStaticMetadata(this, "adjustmentStagingControlID", "CM_ADJ_STG                    ", "ADJ_STG_CTL_ID                ", false, 12, 0));
        /** The status property */
        public final StringProperty status
            = new StringProperty(new SinglePropertyStaticMetadata(this, "status", "CM_ADJ_STG                    ", "BO_STATUS_CD                  ", false, 12, 0));
        /** The division property */
        public final StringProperty division
            = new StringProperty(new SinglePropertyStaticMetadata(this, "division", "CM_ADJ_STG                    ", "CIS_DIVISION                  ", false, 5, 0));
        /** The errorInfo property */
        public final StringProperty errorInfo
            = new StringProperty(new SinglePropertyStaticMetadata(this, "errorInfo", "CM_ADJ_STG                    ", "ERROR_INFO                    ", false, 254, 0));
        /** The eventId property */
        public final StringProperty eventId
            = new StringProperty(new SinglePropertyStaticMetadata(this, "eventId", "CM_ADJ_STG                    ", "EVENT_ID                      ", false, 60, 0));
        /** The isEligibleForArchiving property */
        public final BooleanProperty isEligibleForArchiving
            = new BooleanProperty(new SinglePropertyStaticMetadata(this, "isEligibleForArchiving", "CM_ADJ_STG                    ", "ILM_ARCH_SW                   ", false, 1, 0));
        /** The ilmDate property */
        public final DateProperty ilmDate
            = new DateProperty(new SinglePropertyStaticMetadata(this, "ilmDate", "CM_ADJ_STG                    ", "ILM_DT                        ", false, 10, 0));
        /** The messageCategory property */
        public final IntegerProperty messageCategory
            = new IntegerProperty(new SinglePropertyStaticMetadata(this, "messageCategory", "CM_ADJ_STG                    ", "MESSAGE_CAT_NBR               ", false, 5, 0));
        /** The messageNumber property */
        public final IntegerProperty messageNumber
            = new IntegerProperty(new SinglePropertyStaticMetadata(this, "messageNumber", "CM_ADJ_STG                    ", "MESSAGE_NBR                   ", false, 5, 0));
        /** The saType property */
        public final StringProperty saType
            = new StringProperty(new SinglePropertyStaticMetadata(this, "saType", "CM_ADJ_STG                    ", "SA_TYPE_CD                    ", false, 8, 0));
        /** The statusDateTime property */
        public final DateTimeProperty statusDateTime
            = new DateTimeProperty(new SinglePropertyStaticMetadata(this, "statusDateTime", "CM_ADJ_STG                    ", "STATUS_UPD_DTTM               ", false, 26, 0));
        /** The uploadDateTime property */
        public final DateTimeProperty uploadDateTime
            = new DateTimeProperty(new SinglePropertyStaticMetadata(this, "uploadDateTime", "CM_ADJ_STG                    ", "UPLD_DTTM                     ", false, 26, 0));

        /** The ID property */
        public final IdProperty<com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging> id = new IdProperty<com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging>(this, "CM_ADJ_STG                    ", "PK_CM_ADJ_ST", "CM  ");
       

            
        // References to parent entities PropertyHolders    
    
        /** An array of all the properties */
        private final Property[] ALL_PROPERTIES = {
           accountNumber,adjustmentCategory,adjustmentStagingControlID,status,division,errorInfo,eventId,isEligibleForArchiving,ilmDate,messageCategory,messageNumber,saType,statusDateTime,uploadDateTime,               id
};


        public static class ReferenceProperty
            extends ReferencePropertyValue {

            //~ Instance fields ------------------------------------------------------------------------------

            private ReferencePropertyValue oldValue;

            //~ Constructors ---------------------------------------------------------------------------------

            public ReferenceProperty(PropertyHolder holder, String propertyName, String tableName,
                                         String dbName, String owner,
                                         boolean isInPK,
                                         boolean isOptional) {
                super(holder, propertyName, tableName, dbName, owner, isInPK, isOptional);
            }

            //~ Methods --------------------------------------------------------------------------------------

            public ReferencePropertyValue getOldValue() {
                if (oldValue == null) {
                    oldValue = new ReferencePropertyValue(getPropertyHolder(),
                                                              getPropertyName(),
                                                              getTableName(),
                                                              getDbName(), getOwner(),
                                                              isPKForeignKeyProperty(),
                                                              isOptionalFKProperty());
                }
                return oldValue;
            }


            /**
             * @see com.splwg.base.api.changehandling.OldValueContainingProperty#wasChanged()
             */
            public Condition wasChanged() {
                 return isEqualTo(getOldValue()).not();
            }

            /**
             * @see com.splwg.base.api.changehandling.PropertyValue#isOldVersion()
             */
            @Override
            public boolean isOldVersion() {
                return false;
            }

            /**
             * @see com.splwg.base.api.changehandling.PropertyValue#isOldVersion()
             */
            @Override
            public boolean isNewVersion() {
                return true;
            }
            
        }

        public static class ReferencePropertyValue
            extends ManyToOnePropertyValue<CmAdjustmentStaging> {

            //~ Constructors ---------------------------------------------------------------------------------

            public ReferencePropertyValue(PropertyHolder holder, String propertyName, String tableName,
                                              String dbName, String owner,
                                              boolean isInPK,
                                              boolean isOptional) {
                super(holder, propertyName, tableName, dbName, owner, isInPK, isOptional);
            }

            //~ Methods --------------------------------------------------------------------------------------

            public Condition isEqualTo(ReferencePropertyValue other) {
                return privateEqualTo(other);
            }

            public Condition isEqualTo(com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_Id id) {
                return privateEqualTo(id);
            }

            @Override
            public String getReferencedTableName() {
                return "CM_ADJ_STG";
            }
        }
   	
    }
}
