/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: SingleFieldIdClass.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/SingleFieldIdClass.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.ilm;

import java.math.BigInteger;
import com.splwg.base.api.datatypes.IntegerId;

import java.util.Map;


/**
  * Generated Id class for CmAdjustmentStaging
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public class CmAdjustmentStaging_Id extends IntegerId<CmAdjustmentStaging> {
    public static final int FIELD_SIZE = 12;
    public static final CmAdjustmentStaging_Id NULL = new CmAdjustmentStaging_Id (
         BigInteger.ZERO
    );

    /* public constructor */
    /**
     * Creates a new CmAdjustmentStaging_Id object.
     *
      * @param adjustmentUploadId the adjustmentUploadId
     */
    public CmAdjustmentStaging_Id(
         BigInteger adjustmentUploadId
      ) {
      super(
        adjustmentUploadId
            );
    }

    /**
      * Create a new CmAdjustmentStaging_Id object from the passed map of field/value pairs:
      *            Key           Type
      *     adjustmentUploadId = a BigInteger
      *
      * @param valuePairs a Map of key/value pairs
      */
    public CmAdjustmentStaging_Id(Map valuePairs) {
        super(valuePairs);
    }

    /**
     * @see com.splwg.base.api.datatypes.SingleFieldId#getFieldName()
     */
    @Override
    public String getFieldName() {
         return "ADJ_STG_UP_ID";
    }

    /**
     * @see com.splwg.base.api.datatypes.EntityId#getEntityName()
     */
    @Override
    public String getEntityName() {
        return "cmAdjustmentStaging";
    }

    /**
      * @see com.splwg.base.api.datatypes.IntegerId#fieldSize()
      */
    @Override      
    public int fieldSize() {
        return FIELD_SIZE;
    }

    @Override      
    protected Class getUserTypeClass() {
        return com.splwg.base.support.hibernatetypes.IntegerIdType.class;
    }

    


    @Override
    	public Class<CmAdjustmentStaging> getEntityInterface() {
	        return CmAdjustmentStaging.class;    
    }
}
