/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: BaseClass.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/BaseClass.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.ilm; 

import java.math.BigInteger;

import com.splwg.base.api.datatypes.Bool;
import com.splwg.base.api.datatypes.Date;
import com.splwg.base.api.datatypes.DateTime;
import com.splwg.base.api.DataTransferObject;


/**
  * Generated base class for CmAdjustmentStaging
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public abstract class CmAdjustmentStaging_Gen
                 extends com.splwg.base.support.api.AbstractBusinessEntity<com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging>
                 {                                  
    
    /**
     * Default constructor.
     */
    public CmAdjustmentStaging_Gen () {
       // empty
    }
    
    /**
     * Get the persistent instance of the entity
     *
     */
    protected CmAdjustmentStaging thisEntity(){
       return (CmAdjustmentStaging)this;
    }

    /* the prime key */
    /**
      * Get the id property
      *
      * @return the id
      */
    public com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_Id getId() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");
    }

    /* simple persistent fields */
    /**
      * Get the accountNumber property
      *
      * @return accountNumber
      */
    public String getAccountNumber() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the adjustmentCategory property
      *
      * @return adjustmentCategory
      */
    public String getAdjustmentCategory() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the adjustmentStagingControlID property
      *
      * @return adjustmentStagingControlID
      */
    public BigInteger getAdjustmentStagingControlID() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the status property
      *
      * @return status
      */
    public String getStatus() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the division property
      *
      * @return division
      */
    public String getDivision() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the errorInfo property
      *
      * @return errorInfo
      */
    public String getErrorInfo() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the eventId property
      *
      * @return eventId
      */
    public String getEventId() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the isEligibleForArchiving property
      *
      * @return isEligibleForArchiving
      */
    public Bool getIsEligibleForArchiving() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the ilmDate property
      *
      * @return ilmDate
      */
    public Date getIlmDate() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the messageCategory property
      *
      * @return messageCategory
      */
    public BigInteger getMessageCategory() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the messageNumber property
      *
      * @return messageNumber
      */
    public BigInteger getMessageNumber() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the saType property
      *
      * @return saType
      */
    public String getSaType() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the statusDateTime property
      *
      * @return statusDateTime
      */
    public DateTime getStatusDateTime() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the uploadDateTime property
      *
      * @return uploadDateTime
      */
    public DateTime getUploadDateTime() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }

    /* FK properties */

    /* optional FK properties */

    /**
      * Modify this object's fields from its corresponding data transfer object
      *
      * @param lowestDto the (lowest casted) data transfer object to set from
      */
    public void setDTO(com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_DTO lowestDto) {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }

    /**
      * Get the Data transfer object with this business entity's values
      *
      * @return a Data transfer object based upon this entity
      */
    @Override
    public com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_DTO getDTO() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }




    /**
    * Set this object's fields from its corresponding data transfer object.
    * Accept a generic DTO, cast to my specific type.  Useful for framework code.
    *
    * @param dto the data transfer object
    */
    @Override
    public void setDTO(DataTransferObject<com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging> dto) {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }

     /**
     * @see  com.splwg.base.api.PersistentEntity#delete()
     */
    public void delete() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }


}
