/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: HibernatePOJOClass.vm
 * $File: //FW/2.0.5/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/HibernatePOJOClass.vm $
 * $DateTime: 2005/06/27 09:37:49 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.ilm; 

import com.splwg.base.api.datatypes.Bool;
import com.splwg.base.api.datatypes.Date;
import com.splwg.base.api.datatypes.DateTime;


import java.math.BigInteger;

public class CmAdjustmentStaging_POJO
{
    /* the prime key */
    private com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_POJO_Id id;
    /* simple persistent fields */
    private String accountNumber;
    private String adjustmentCategory;
    private BigInteger adjustmentStagingControlID;
    private String status;
    private String division;
    private String errorInfo;
    private String eventId;
    private Bool isEligibleForArchiving;
    private Date ilmDate;
    private BigInteger messageCategory;
    private BigInteger messageNumber;
    private String saType;
    private DateTime statusDateTime;
    private DateTime uploadDateTime;
    /* FK properties */
    /* optional FK properties */


    //~ Methods ------------------------------------------------------------------------------------------

    /* the prime key */
    public com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_POJO_Id getId() {
        return id;
    }
    
    public void setId(com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_POJO_Id newId) {
        this.id = newId;
    }

    /* simple persistent fields */
    public String getAccountNumber() {
        return accountNumber;
    }
    
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    public String getAdjustmentCategory() {
        return adjustmentCategory;
    }
    
    public void setAdjustmentCategory(String value) {
        this.adjustmentCategory = value;
    }

    public BigInteger getAdjustmentStagingControlID() {
        return adjustmentStagingControlID;
    }
    
    public void setAdjustmentStagingControlID(BigInteger value) {
        this.adjustmentStagingControlID = value;
    }

    public String getStatus() {
        return status;
    }
    
    public void setStatus(String value) {
        this.status = value;
    }

    public String getDivision() {
        return division;
    }
    
    public void setDivision(String value) {
        this.division = value;
    }

    public String getErrorInfo() {
        return errorInfo;
    }
    
    public void setErrorInfo(String value) {
        this.errorInfo = value;
    }

    public String getEventId() {
        return eventId;
    }
    
    public void setEventId(String value) {
        this.eventId = value;
    }

    public Bool getIsEligibleForArchiving() {
        return isEligibleForArchiving;
    }
    
    public void setIsEligibleForArchiving(Bool value) {
        this.isEligibleForArchiving = value;
    }

    public Date getIlmDate() {
        return ilmDate;
    }
    
    public void setIlmDate(Date value) {
        this.ilmDate = value;
    }

    public BigInteger getMessageCategory() {
        return messageCategory;
    }
    
    public void setMessageCategory(BigInteger value) {
        this.messageCategory = value;
    }

    public BigInteger getMessageNumber() {
        return messageNumber;
    }
    
    public void setMessageNumber(BigInteger value) {
        this.messageNumber = value;
    }

    public String getSaType() {
        return saType;
    }
    
    public void setSaType(String value) {
        this.saType = value;
    }

    public DateTime getStatusDateTime() {
        return statusDateTime;
    }
    
    public void setStatusDateTime(DateTime value) {
        this.statusDateTime = value;
    }

    public DateTime getUploadDateTime() {
        return uploadDateTime;
    }
    
    public void setUploadDateTime(DateTime value) {
        this.uploadDateTime = value;
    }


    /* FK properties */

    /* optional FK properties */


   
    @Override
    public String toString() {
        return "Entity: " + id.toString();
    }
}
