/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: HibernatePOJOIdUserType.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/HibernatePOJOIdUserType.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.ilm;


import com.splwg.base.api.datatypes.HibernatePOJOIntegerId;
import com.splwg.base.support.hibernatetypes.HibernatePOJOIntegerIdType;

public class CmAdjustmentStaging_POJO_IdType extends HibernatePOJOIntegerIdType {

    @Override
    public Class returnedClass() {
        return CmAdjustmentStaging_POJO_Id.class;
    }
    
    @Override
    protected HibernatePOJOIntegerId getId(java.math.BigInteger value) {
        return new CmAdjustmentStaging_POJO_Id(value);
    }
    

}
