/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: DTOClass.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/DTOClass.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.ilm;

import com.splwg.base.api.datatypes.Bool;
import com.splwg.base.api.datatypes.Date;
import com.splwg.base.api.datatypes.DateTime;
import java.math.BigInteger;



import com.splwg.base.support.impl.AbstractDataTransferObject;

/**
 * Data transfer object for CmAdjustmentStaging
 *
 * @author Generated by splDev.artifactGenerator
 */
public class CmAdjustmentStaging_DTO extends AbstractDataTransferObject<CmAdjustmentStaging>  {

    /* persistent fields */
    private String accountNumber = "";
    private String adjustmentCategory = "";
    private BigInteger adjustmentStagingControlID = BigInteger.ZERO;
    private String status = "";
    private String division = "";
    private String errorInfo = "";
    private String eventId = "";
    private Bool isEligibleForArchiving = Bool.FALSE;
    private Date ilmDate = null;
    private BigInteger messageCategory = BigInteger.ZERO;
    private BigInteger messageNumber = BigInteger.ZERO;
    private String saType = "";
    private DateTime statusDateTime = null;
    private DateTime uploadDateTime = null;
    /* Many-to-ones and optional FKs*/
    /**
      * Create a new CmAdjustmentStaging_DTO
      */
    public CmAdjustmentStaging_DTO() {
      // empty constructor
    }

    @Override
    public String entityName() {
        return "cmAdjustmentStaging";
    }

    /**
      * Get the id property
      *
      * @return the id
      */
    @Override
    public com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_Id getId() {
        return (com.splwg.cm.domain.wp.ilm.CmAdjustmentStaging_Id) getAbstractId();
    }

    /* persistent fields */
    /**
      * Get the accountNumber property
      *
      * @return accountNumber
      */
    public String getAccountNumber() {
        return accountNumber;
    }
    /**
      * Set the accountNumber property
      * The string will be truncated to fit the field's size of 30
      *
      * @param value the new value
      */
    public void setAccountNumber(String value) {
        this.accountNumber = modifyVarCharString("accountNumber", value, 30 );
    }
    /**
      * Get the adjustmentCategory property
      *
      * @return adjustmentCategory
      */
    public String getAdjustmentCategory() {
        return adjustmentCategory;
    }
    /**
      * Set the adjustmentCategory property
      *
      * @param value the new value
      */
    public void setAdjustmentCategory(String value) {
        this.adjustmentCategory = value;
    }
    /**
      * Get the adjustmentStagingControlID property
      *
      * @return adjustmentStagingControlID
      */
    public BigInteger getAdjustmentStagingControlID() {
        return adjustmentStagingControlID;
    }
    /**
      * Set the adjustmentStagingControlID property
      *
      * @param value the new value
      */
    public void setAdjustmentStagingControlID(BigInteger value) {
        this.adjustmentStagingControlID = value;
    }
    /**
      * Get the status property
      *
      * @return status
      */
    public String getStatus() {
        return status;
    }
    /**
      * Set the status property
      *
      * @param value the new value
      */
    public void setStatus(String value) {
        this.status = value;
    }
    /**
      * Get the division property
      *
      * @return division
      */
    public String getDivision() {
        return division;
    }
    /**
      * Set the division property
      *
      * @param value the new value
      */
    public void setDivision(String value) {
        this.division = value;
    }
    /**
      * Get the errorInfo property
      *
      * @return errorInfo
      */
    public String getErrorInfo() {
        return errorInfo;
    }
    /**
      * Set the errorInfo property
      * The string will be truncated to fit the field's size of 254
      *
      * @param value the new value
      */
    public void setErrorInfo(String value) {
        this.errorInfo = modifyVarCharString("errorInfo", value, 254 );
    }
    /**
      * Get the eventId property
      *
      * @return eventId
      */
    public String getEventId() {
        return eventId;
    }
    /**
      * Set the eventId property
      *
      * @param value the new value
      */
    public void setEventId(String value) {
        this.eventId = value;
    }
    /**
      * Get the isEligibleForArchiving property
      *
      * @return isEligibleForArchiving
      */
    public Bool getIsEligibleForArchiving() {
        return isEligibleForArchiving;
    }
    /**
      * Set the isEligibleForArchiving property
      *
      * @param value the new value
      */
    public void setIsEligibleForArchiving(Bool value) {
        this.isEligibleForArchiving = value;
    }
    /**
      * Get the ilmDate property
      *
      * @return ilmDate
      */
    public Date getIlmDate() {
        return ilmDate;
    }
    /**
      * Set the ilmDate property
      *
      * @param value the new value
      */
    public void setIlmDate(Date value) {
        this.ilmDate = value;
    }
    /**
      * Get the messageCategory property
      *
      * @return messageCategory
      */
    public BigInteger getMessageCategory() {
        return messageCategory;
    }
    /**
      * Set the messageCategory property
      *
      * @param value the new value
      */
    public void setMessageCategory(BigInteger value) {
        this.messageCategory = value;
    }
    /**
      * Get the messageNumber property
      *
      * @return messageNumber
      */
    public BigInteger getMessageNumber() {
        return messageNumber;
    }
    /**
      * Set the messageNumber property
      *
      * @param value the new value
      */
    public void setMessageNumber(BigInteger value) {
        this.messageNumber = value;
    }
    /**
      * Get the saType property
      *
      * @return saType
      */
    public String getSaType() {
        return saType;
    }
    /**
      * Set the saType property
      *
      * @param value the new value
      */
    public void setSaType(String value) {
        this.saType = value;
    }
    /**
      * Get the statusDateTime property
      *
      * @return statusDateTime
      */
    public DateTime getStatusDateTime() {
        return statusDateTime;
    }
    /**
      * Set the statusDateTime property
      *
      * @param value the new value
      */
    public void setStatusDateTime(DateTime value) {
        this.statusDateTime = value;
    }
    /**
      * Get the uploadDateTime property
      *
      * @return uploadDateTime
      */
    public DateTime getUploadDateTime() {
        return uploadDateTime;
    }
    /**
      * Set the uploadDateTime property
      *
      * @param value the new value
      */
    public void setUploadDateTime(DateTime value) {
        this.uploadDateTime = value;
    }

    /* Many-to-ones and optional FKs*/


    /* canonical methods */

    @Override
    public CmAdjustmentStaging newEntity() {
         return abstractNewEntity();
    }
}
