/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: AlgorithmComponentGenClass.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/AlgorithmComponentGenClass.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.support.algorithm.AbstractAlgorithmComponent;
import com.splwg.ccb.domain.pricing.priceitem.PriceItem_Id;
import com.splwg.ccb.domain.pricing.priceitem.PriceItem;

/**
  * Generated super class for the cmDeleteZeroMinSegment algorithm component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public abstract class CmDeleteZeroMinSegment_Gen extends AbstractAlgorithmComponent
         implements CmDeleteZeroMinSegment
{

    public final PriceItem getPriceItem () {
        String idValue = getSoftParameter(0);
	        if (idValue == null) reportRequiredParameter("priceItem",0);
	        PriceItem_Id id = new PriceItem_Id(idValue);
        PriceItem priceItem = id.getEntity();
	        validateSoftEntityExists("priceItem",0 ,id, priceItem);
	        return priceItem;
    }

    protected final void validateParameterTypes() {
        getPriceItem();

    }
   

}
