/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: ComponentInterface.VM
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/ComponentInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.api.BusinessComponent;
import com.splwg.ccb.domain.admin.customerClass.CustomerClassPreBillCompletionAlgorithmSpot; 

/**
  * Interface for the cmDeleteZeroMinSegment component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public interface CmDeleteZeroMinSegment extends BusinessComponent
                 , CustomerClassPreBillCompletionAlgorithmSpot 
                  {


    /**
      * 
      */
     
     void invoke() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getAllowReopeningOfBills() ;

    /**
      * 
      */
     
     com.splwg.ccb.api.lookup.BillCompletionActionLookup getBillCompletionAction() ;

    /**
      * 
      */
     
     com.splwg.shared.common.ServerMessage getServerMessage() ;

    /**
      * 
      */
     
     void setAccount(com.splwg.ccb.domain.customerinfo.account.Account arg0) ;

    /**
      * 
      */
     
     void setAccountingDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setAllowReopeningOfBills(com.splwg.base.api.datatypes.Bool arg0) ;

    /**
      * 
      */
     
     void setBill(com.splwg.ccb.domain.billing.bill.Bill arg0) ;

    /**
      * 
      */
     
     void setBillDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setBillSegments(java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegment> arg0) ;

    /**
      * 
      */
     
     void setCreditNoteForBill(com.splwg.ccb.domain.billing.bill.Bill arg0) ;

}
