/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: ComponentInterface.VM
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/ComponentInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.api.BusinessComponent;
import com.splwg.ccb.domain.banking.transactionFeed.transactionFeedAgg.algorithm.TransactionProductDerivationPostProcessingAlgorithmSpot; 

/**
  * Interface for the cmNegateTransactionVolumeAlgComp component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public interface CmNegateTransactionVolumeAlgComp extends BusinessComponent
                 , TransactionProductDerivationPostProcessingAlgorithmSpot 
                  {


    /**
      * 
      */
     
     void setTransactionDetailVO(com.splwg.ccb.domain.banking.transactionFeed.transactionFeedAgg.vo.TransactionDetailVO paramTransactionDetailVO) ;

    /**
      * 
      */
     
     com.splwg.ccb.domain.banking.transactionFeed.transactionFeedAgg.vo.TransactionDetailVO getTransactionDetailVO() ;

    /**
      * 
      */
     
     void invoke() ;

}
