/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: AlgorithmComponentGenClass.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/AlgorithmComponentGenClass.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.support.algorithm.AbstractAlgorithmComponent;

/**
  * Generated super class for the cmRecurringBillableChargeBillSegmentCreation algorithm component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public abstract class CmRecurringBillableChargeBillSegmentCreation_Gen extends AbstractAlgorithmComponent
         implements CmRecurringBillableChargeBillSegmentCreation
{

    public final String getCharacteristicTypeForAccount () {
	    String result = getSoftParameter(0);
		if (result == null) reportRequiredParameter("characteristicTypeForAccount",0);
	    return result;
    }

    public final String getCharacteristicTypeForPerson () {
	    String result = getSoftParameter(1);
		if (result == null) reportRequiredParameter("characteristicTypeForPerson",1);
	    return result;
    }

    public final String getCharacteristicTypeForPriceList () {
	    String result = getSoftParameter(2);
		if (result == null) reportRequiredParameter("characteristicTypeForPriceList",2);
	    return result;
    }

    public final String getCharacteristicTypeForPriceAssignId () {
	    String result = getSoftParameter(3);
		if (result == null) reportRequiredParameter("characteristicTypeForPriceAssignId",3);
	    return result;
    }

    public final String getCharacteristicTypeForTrialBillId () {
	    String result = getSoftParameter(4);
	    return result;
    }

    protected final void validateParameterTypes() {
        getCharacteristicTypeForAccount();
        getCharacteristicTypeForPerson();
        getCharacteristicTypeForPriceList();
        getCharacteristicTypeForPriceAssignId();
        getCharacteristicTypeForTrialBillId();

    }
   

}
