/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: ComponentInterface.VM
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/ComponentInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.api.BusinessComponent;
import com.splwg.ccb.domain.admin.billSegmentType.BillSegmentTypeBillSegmentCreationAlgorithmSpot; 

/**
  * Interface for the cmRecurringBillableChargeBillSegmentCreation component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public interface CmRecurringBillableChargeBillSegmentCreation extends BusinessComponent
                 , BillSegmentTypeBillSegmentCreationAlgorithmSpot 
                  {


    /**
      * 
      */
     
     void setMustRetainReads(com.splwg.base.api.datatypes.Bool mustRetainReads) ;

    /**
      * 
      */
     
     void setMustRetainItems(com.splwg.base.api.datatypes.Bool mustRetainItems) ;

    /**
      * 
      */
     
     void setMustRetainServiceQuantities(com.splwg.base.api.datatypes.Bool mustRetainServiceQuantities) ;

    /**
      * 
      */
     
     void setServiceAgreement(com.splwg.ccb.domain.customerinfo.serviceAgreement.ServiceAgreement serviceAgreement) ;

    /**
      * 
      */
     
     void setBillSegmentAction(com.splwg.ccb.api.lookup.BillSegmentActionLookup billSegmentAction) ;

    /**
      * 
      */
     
     void setConsumptionStartDate(com.splwg.base.api.datatypes.Date consumptionStartDate) ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getConsumptionStartDate() ;

    /**
      * 
      */
     
     void setConsumptionEndDate(com.splwg.base.api.datatypes.Date consumptionEndDate) ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getConsumptionEndDate() ;

    /**
      * 
      */
     
     void setServiceAgreementStartDate(com.splwg.base.api.datatypes.Date serviceAgreementStartDate) ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getServiceAgreementStartDate() ;

    /**
      * 
      */
     
     void setServiceAgreementEndDate(com.splwg.base.api.datatypes.Date serviceAgreementEndDate) ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getServiceAgreementEndDate() ;

    /**
      * 
      */
     
     void setIntervalBillingStartDayOption(com.splwg.ccb.api.lookup.IntervalBillingStartDayOptionLookup intervalBillingStartDayOption) ;

    /**
      * 
      */
     
     com.splwg.ccb.api.lookup.IntervalBillingStartDayOptionLookup getIntervalBillingStartDayOption() ;

    /**
      * 
      */
     
     void setIntervalBilllingCutoffTime(com.splwg.base.api.datatypes.Time intervalBillingCutOffTime) ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Time getIntervalBillingCutoffTime() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Money getRecurringChargeAmount() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Money getProratedRecurringChargeAmount() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getMustSkipServiceAgreement() ;

    /**
      * 
      */
     
     com.splwg.ccb.api.lookup.SkipSaReasonLookup getSkipSaReason() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getMustRestartGeneration() ;

    /**
      * 
      */
     
     com.splwg.ccb.api.lookup.ExitIterationLoopLookup getExitLoopCheck() ;

    /**
      * 
      */
     
     void setBillSegmentData(com.splwg.ccb.domain.billing.billSegment.BillSegmentData billSegmentData) ;

    /**
      * 
      */
     
     com.splwg.ccb.domain.billing.billSegment.BillSegmentData getBillSegmentData() ;

    /**
      * 
      */
     
     void setBillSegmentReadData(java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentReadData> billSegmentReadData) ;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentReadData> getBillSegmentReadData() ;

    /**
      * 
      */
     
     void setBillSegmentGeneratorData(com.splwg.ccb.domain.billing.billSegment.BillSegmentGeneratorData billSegmentGeneratorData) ;

    /**
      * 
      */
     
     com.splwg.ccb.domain.billing.billSegment.BillSegmentGeneratorData getBillSegmentGeneratorData() ;

    /**
      * 
      */
     
     void setBillSegmentItemData(java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentItemData> billSegmentItemData) ;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentItemData> getBillSegmentItemData() ;

    /**
      * 
      */
     
     void setBillSegmentServiceQuantityData(java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentServiceQuantityData> billSegmentServiceQuantityData) ;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentServiceQuantityData> getBillSegmentServiceQuantityData() ;

    /**
      * 
      */
     
     void setBillSegmentCalculationHeaderData(            java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentCalculationHeaderData> billSegmentCalculationHeaderData) ;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentCalculationHeaderData> getBillSegmentCalculationHeaderData() ;

    /**
      * 
      */
     
     void setBillSegment(com.splwg.ccb.domain.billing.billSegment.BillSegment billSegment) ;

    /**
      * 
      */
     
     void setPreviousFrozenBillSegment(com.splwg.ccb.domain.billing.billSegment.BillSegment billSegment) ;

    /**
      * 
      */
     
     void invoke() ;

}
