/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: ComponentInterface.VM
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/ComponentInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.api.BusinessComponent;
import com.splwg.ccb.domain.admin.rulesengine.rule.RuleCriteriaFieldAlgorithmSpot; 

/**
  * Interface for the cmRuleOutParameterVal component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public interface CmRuleOutParameterVal extends BusinessComponent
                 , RuleCriteriaFieldAlgorithmSpot 
                  {


    /**
      * 
      */
     
     void invoke() ;

    /**
      * 
      */
     
     void setRuleParam(com.splwg.ccb.domain.admin.rulesengine.RuleParameters ruleParam) ;

    /**
      * 
      */
     
     void setCriteriaFieldName(java.lang.String criteriaFieldName) ;

    /**
      * 
      */
     
     void setCriteriaFieldValue(java.lang.String criteriaFieldValue) ;

    /**
      * 
      */
     
     java.lang.String getCriteriaFieldName() ;

    /**
      * 
      */
     
     java.lang.String getCriteriaFieldValue() ;

    /**
      * 
      */
     
     void setInputParameters(com.splwg.ccb.domain.admin.rulesengine.RuleParameters ruleParam) ;

    /**
      * 
      */
     
     void setRule(com.splwg.ccb.domain.admin.rulesengine.rule.Rule rule) ;

}
