/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: ComponentInterface.VM
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/ComponentInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.api.BusinessComponent;
import com.splwg.ccb.domain.admin.serviceAgreementType.SaTypePostProcessingAlgorithmSpot; 

/**
  * Interface for the cmSkipPostProcessingBillingAlgComp component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public interface CmSkipPostProcessingBillingAlgComp extends BusinessComponent
                 , SaTypePostProcessingAlgorithmSpot 
                  {


    /**
      * Main processing

      */
     
     void invoke() ;

    /**
      * 
      */
     
     java.lang.String getAccountId() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getAccountingDate() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getAllowEstSw() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getAsgnSeqNbrSw() ;

    /**
      * 
      */
     
     java.math.BigInteger getBatchRunNo() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getBillCompleteSw() ;

    /**
      * 
      */
     
     java.lang.String getBillCycCode() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getBillDate() ;

    /**
      * 
      */
     
     java.lang.String getBillGenType() ;

    /**
      * 
      */
     
     java.lang.String getBillId() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getBillOptSw() ;

    /**
      * 
      */
     
     java.lang.String getBsbsxAccountId() ;

    /**
      * 
      */
     
     java.lang.String getBsbsxBillCycCode() ;

    /**
      * 
      */
     
     java.lang.String getBsbsxBillId() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getBsbsxEndDate() ;

    /**
      * 
      */
     
     java.lang.String getBsbsxSaId() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getBsbsxStartDate() ;

    /**
      * 
      */
     
     java.lang.String getCisDivision() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getCutOffDate() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getEndDate() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getEstDate() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getFreezeCmpSw() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getMidTrxCommitSw() ;

    /**
      * 
      */
     
     java.lang.String getSaId() ;

    /**
      * 
      */
     
     java.lang.String getSaTypeCode() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getSkipSw() ;

    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Date getStartDate() ;

    /**
      * 
      */
     
     java.lang.String getTrialBillId() ;

    /**
      * 
      */
     
     java.lang.String getUpdateSw() ;

    /**
      * 
      */
     
     void setAccountId(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setAccountingDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setAllowEstSw(com.splwg.base.api.datatypes.Bool arg0) ;

    /**
      * 
      */
     
     void setAsgnSeqNbrSw(com.splwg.base.api.datatypes.Bool arg0) ;

    /**
      * 
      */
     
     void setBatchRunNo(java.math.BigInteger arg0) ;

    /**
      * 
      */
     
     void setBillCompleteSw(com.splwg.base.api.datatypes.Bool arg0) ;

    /**
      * 
      */
     
     void setBillCycCode(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setBillDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setBillGenType(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setBillId(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setBillOptSw(com.splwg.base.api.datatypes.Bool arg0) ;

    /**
      * 
      */
     
     void setBsbsxAccountId(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setBsbsxBillCycCode(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setBsbsxBillId(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setBsbsxEndDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setBsbsxSaId(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setBsbsxStartDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setCisDivision(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setCutOffDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setEndDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setEstDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setFreezeCmpSw(com.splwg.base.api.datatypes.Bool arg0) ;

    /**
      * 
      */
     
     void setMidTrxCommitSw(com.splwg.base.api.datatypes.Bool arg0) ;

    /**
      * 
      */
     
     void setSaId(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setSaTypeCode(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setSkipSw(com.splwg.base.api.datatypes.Bool arg0) ;

    /**
      * 
      */
     
     void setStartDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setTrialBillId(java.lang.String arg0) ;

    /**
      * 
      */
     
     void setUpdateSw(java.lang.String arg0) ;

}
