/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: AlgorithmComponentGenClass.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/AlgorithmComponentGenClass.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.support.algorithm.AbstractAlgorithmComponent;

/**
  * Generated super class for the cmSkipPostProcessingBillingAlgComp algorithm component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public abstract class CmSkipPostProcessingBillingAlgComp_Gen extends AbstractAlgorithmComponent
         implements CmSkipPostProcessingBillingAlgComp
{

    protected final void validateParameterTypes() {
        // empty

    }
   

}
