/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: ComponentInterface.VM
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/ComponentInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.api.BusinessComponent;
import com.splwg.ccb.domain.rate.rateComponent.RateComponentValueAlgorithmSpot; 

/**
  * Interface for the customTierAlgorithm component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public interface CustomTierAlgorithm extends BusinessComponent
                 , RateComponentValueAlgorithmSpot 
                  {


    /**
      * 
      */
     
     com.splwg.ccb.domain.rate.ApplyRateData getApplyRateData()	;

    /**
      * 
      */
     
     com.splwg.ccb.domain.rate.rateVersion.ApplyRateVersionData getApplyRateVersionData()	;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentCalculationHeaderData> getBillSegmentCalculationHeaderData()	;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentItemData> getBillSegmentItemData()	;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentServiceQuantityData> getBillSegmentServiceQuantityData()	;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.common.characteristic.CharacteristicData> getCharacteristicData()	;

    /**
      * 
      */
     
     com.ibm.icu.math.BigDecimal getValue()	;

    /**
      * 
      */
     
     void setValue(com.ibm.icu.math.BigDecimal value)	;

    /**
      * 
      */
     
     void setApplyRateData(com.splwg.ccb.domain.rate.ApplyRateData applyRateData)	;

    /**
      * 
      */
     
     void setApplyRateVersionData(com.splwg.ccb.domain.rate.rateVersion.ApplyRateVersionData applyRateVersionData)	;

    /**
      * 
      */
     
     void setBillSegmentCalculationHeaderData(java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentCalculationHeaderData> billSegmentCalculationHeaderData)	;

    /**
      * 
      */
     
     void setBillSegmentItemData(java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentItemData> billSegmentItemData)	;

    /**
      * 
      */
     
     void setBillSegmentServiceQuantityData(java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentServiceQuantityData> billSegmentSqData)	;

    /**
      * 
      */
     
     void setCharacteristicData(java.util.List<com.splwg.ccb.domain.common.characteristic.CharacteristicData> characteristicData)	;

    /**
      * 
      */
     
     void setCrossReferenceAmount(com.ibm.icu.math.BigDecimal crossReferenceAmount)	;

    /**
      * 
      */
     
     void setCrossReferenceFound(com.splwg.base.api.datatypes.Bool crossReferenceFound)	;

    /**
      * 
      */
     
     void setCrossReferenceServiceQuantity(com.ibm.icu.math.BigDecimal crossReferenceServiceQuantity)	;

    /**
      * 
      */
     
     void setRateComponent(com.splwg.ccb.domain.rate.rateComponent.RateComponent rateComponent)	;

    /**
      * 
      */
     
     void getValueAmount()	;

    /**
      * 
      */
     
     com.ibm.icu.math.BigDecimal getAggSqQuantity()	;

    /**
      * 
      */
     
     java.lang.String getPriceCompId()	;

    /**
      * 
      */
     
     void setAggSqQuantity(com.ibm.icu.math.BigDecimal aggSqQuantity)	;

    /**
      * 
      */
     
     void setPriceCompId(java.lang.String priceCompId)	;

    /**
      * Main processing.

      */
     
     void invoke()	;

    /**
      * 
      */
     
     java.lang.String getAccountID()	;

}
