/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: AlgorithmComponentGenClass.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/AlgorithmComponentGenClass.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.support.algorithm.AbstractAlgorithmComponent;

/**
  * Generated super class for the minChargeBsegTotNetChargeCalc algorithm component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public abstract class MinChargeBsegTotNetChargeCalc_Gen extends AbstractAlgorithmComponent
         implements MinChargeBsegTotNetChargeCalc
{

    public final String getDstIdValue1 () {
	    String result = getSoftParameter(0);
		if (result == null) reportRequiredParameter("DstIdValue1",0);
	    return result;
    }

    public final String getDstIdValue2 () {
	    String result = getSoftParameter(1);
		if (result == null) reportRequiredParameter("DstIdValue2",1);
	    return result;
    }

    public final String getProductFlagValue () {
	    String result = getSoftParameter(2);
		if (result == null) reportRequiredParameter("ProductFlagValue",2);
	    return result;
    }

    protected final void validateParameterTypes() {
        getDstIdValue1();
        getDstIdValue2();
        getProductFlagValue();

    }
   

}
