/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: ComponentInterface.VM
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/ComponentInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.api.BusinessComponent;
import com.splwg.ccb.domain.rate.rateComponent.RateComponentValueAlgorithmSpot; 

/**
  * Interface for the minChargeBsegTotNetChargeCalc component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public interface MinChargeBsegTotNetChargeCalc extends BusinessComponent
                 , RateComponentValueAlgorithmSpot 
                  {


    /**
      * 
      */
     
     com.splwg.ccb.domain.rate.ApplyRateData getApplyRateData() ;

    /**
      * 
      */
     
     com.splwg.ccb.domain.rate.rateVersion.ApplyRateVersionData getApplyRateVersionData() ;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentCalculationHeaderData> getBillSegmentCalculationHeaderData() ;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentItemData> getBillSegmentItemData() ;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentServiceQuantityData> getBillSegmentServiceQuantityData() ;

    /**
      * 
      */
     
     java.util.List<com.splwg.ccb.domain.common.characteristic.CharacteristicData> getCharacteristicData() ;

    /**
      * 
      */
     
     com.ibm.icu.math.BigDecimal getValue() ;

    /**
      * 
      */
     
     void setApplyRateData(com.splwg.ccb.domain.rate.ApplyRateData arg0) ;

    /**
      * 
      */
     
     void setApplyRateVersionData(com.splwg.ccb.domain.rate.rateVersion.ApplyRateVersionData arg0) ;

    /**
      * 
      */
     
     void setBillSegmentCalculationHeaderData(			java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentCalculationHeaderData> arg0) ;

    /**
      * 
      */
     
     void setBillSegmentItemData(java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentItemData> arg0) ;

    /**
      * 
      */
     
     void setBillSegmentServiceQuantityData(			java.util.List<com.splwg.ccb.domain.billing.billSegment.BillSegmentServiceQuantityData> arg0) ;

    /**
      * 
      */
     
     void setCharacteristicData(java.util.List<com.splwg.ccb.domain.common.characteristic.CharacteristicData> arg0) ;

    /**
      * 
      */
     
     void setCrossReferenceAmount(com.ibm.icu.math.BigDecimal arg0) ;

    /**
      * 
      */
     
     void setCrossReferenceFound(com.splwg.base.api.datatypes.Bool arg0) ;

    /**
      * 
      */
     
     void setCrossReferenceServiceQuantity(com.ibm.icu.math.BigDecimal arg0) ;

    /**
      * 
      */
     
     void setRateComponent(com.splwg.ccb.domain.rate.rateComponent.RateComponent arg0) ;

    /**
      * invoke() method contains business logic that is executed when the
algorithm is triggered.

      */
     
     void invoke() ;

    /**
      * 
      */
     
     com.ibm.icu.math.BigDecimal getAggSqQuantity() ;

    /**
      * 
      */
     
     java.lang.String getPriceCompId() ;

    /**
      * 
      */
     
     void setAggSqQuantity(com.ibm.icu.math.BigDecimal arg0) ;

    /**
      * 
      */
     
     void setPriceCompId(java.lang.String arg0) ;

}
