/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: ComponentInterface.VM
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/ComponentInterface.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.api.BusinessComponent;
import com.splwg.ccb.domain.admin.serviceAgreementType.SaTypePreBillCompletionAlgorithmSpot; 

/**
  * Interface for the taxAmountCalculation component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public interface TaxAmountCalculation extends BusinessComponent
                 , SaTypePreBillCompletionAlgorithmSpot 
                  {


    /**
      * 
      */
     
     com.splwg.base.api.datatypes.Bool getShouldSkipRemainingAlgorithms() ;

    /**
      * 
      */
     
     void setBill(com.splwg.ccb.domain.billing.bill.Bill arg0) ;

    /**
      * 
      */
     
     void setBillCycle(com.splwg.ccb.domain.admin.billCycle.BillCycle arg0) ;

    /**
      * 
      */
     
     void setEndDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * 
      */
     
     void setServiceAgreementType(com.splwg.ccb.domain.admin.serviceAgreementType.ServiceAgreementType arg0) ;

    /**
      * 
      */
     
     void setStartDate(com.splwg.base.api.datatypes.Date arg0) ;

    /**
      * Main processing.

      */
     
     void invoke() ;

}
