/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: AlgorithmComponentGenClass.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/AlgorithmComponentGenClass.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.algorithm;

import com.splwg.base.support.algorithm.AbstractAlgorithmComponent;

/**
  * Generated super class for the wAFApplication algorithm component
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public abstract class WAFApplication_Gen extends AbstractAlgorithmComponent
         implements WAFApplication
{

    public final String getAcctNbrTypeCd () {
	    String result = getSoftParameter(0);
		if (result == null) reportRequiredParameter("acctNbrTypeCd",0);
	    return result;
    }

    public final String getSaTypeCode () {
	    String result = getSoftParameter(1);
		if (result == null) reportRequiredParameter("saTypeCode",1);
	    return result;
    }

    public final String getWafSaTypeCode () {
	    String result = getSoftParameter(2);
		if (result == null) reportRequiredParameter("wafSaTypeCode",2);
	    return result;
    }

    public final String getWafAdjType () {
	    String result = getSoftParameter(3);
		if (result == null) reportRequiredParameter("wafAdjType",3);
	    return result;
    }

    public final String getWafIndCharacteristictypeCode () {
	    String result = getSoftParameter(4);
		if (result == null) reportRequiredParameter("wafIndCharacteristictypeCode",4);
	    return result;
    }

    protected final void validateParameterTypes() {
        getAcctNbrTypeCd();
        getSaTypeCode();
        getWafSaTypeCode();
        getWafAdjType();
        getWafIndCharacteristictypeCode();

    }
   

}
