/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: HibernatePOJOSingleFieldIdClass.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/HibernatePOJOSingleFieldIdClass.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.entity;

import com.splwg.base.api.datatypes.HibernatePOJOStringId;

/**
  * Generated Id class for CmFtGlAslAccountingId
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public class CmFtGlAslAccountingId_POJO_Id extends HibernatePOJOStringId {
    public static final int FIELD_SIZE = 12;

    public CmFtGlAslAccountingId_POJO_Id(
         String accountingId
      ) {
      super(
        accountingId
            );
    }

    public String getFieldName() {
         return "ACCOUNTING_ID";
    }

    @Override
    public int fieldSize() {
        return FIELD_SIZE;
    }

    
    public String getEntityName() {
        return "cmFtGlAslAccountingId";
    }

    @Override
    public String getSimpleIdClassName() {
        return "CmFtGlAslAccountingId_Id";
    }
        
    
}
