/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: BaseClass.vm
 * $File: //FW/4.0.1/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/BaseClass.vm $
 * $DateTime: 2009/12/17 11:38:59 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.entity; 


import java.math.BigInteger;
import com.splwg.base.api.datatypes.Date;
import com.splwg.base.api.DataTransferObject;


/**
  * Generated base class for CmFtGlFxAccountingId
  *
  * @author Generated by com.splwg.tools.artifactgen.ArtifactGenerator
  */
public abstract class CmFtGlFxAccountingId_Gen
                 extends com.splwg.base.support.api.AbstractBusinessEntity<com.splwg.cm.domain.wp.entity.CmFtGlFxAccountingId>
                 {                                  
    
    /**
     * Default constructor.
     */
    public CmFtGlFxAccountingId_Gen () {
       // empty
    }
    
    /**
     * Get the persistent instance of the entity
     *
     */
    protected CmFtGlFxAccountingId thisEntity(){
       return (CmFtGlFxAccountingId)this;
    }

    /* the prime key */
    /**
      * Get the id property
      *
      * @return the id
      */
    public com.splwg.cm.domain.wp.entity.CmFtGlFxAccountingId_Id getId() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");
    }

    /* simple persistent fields */
    /**
      * Get the glAccount property
      *
      * @return glAccount
      */
    public String getGlAccount() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the accountingDate property
      *
      * @return accountingDate
      */
    public Date getAccountingDate() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the fundCurrency property
      *
      * @return fundCurrency
      */
    public String getFundCurrency() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the binSettlementCurrency property
      *
      * @return binSettlementCurrency
      */
    public String getBinSettlementCurrency() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the counterparty property
      *
      * @return counterparty
      */
    public String getCounterparty() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the businessUnit property
      *
      * @return businessUnit
      */
    public String getBusinessUnit() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the batchControl property
      *
      * @return batchControl
      */
    public String getBatchControl() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }
    /**
      * Get the batchNumber property
      *
      * @return batchNumber
      */
    public BigInteger getBatchNumber() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }

    /* FK properties */

    /* optional FK properties */

    /**
      * Modify this object's fields from its corresponding data transfer object
      *
      * @param lowestDto the (lowest casted) data transfer object to set from
      */
    public void setDTO(com.splwg.cm.domain.wp.entity.CmFtGlFxAccountingId_DTO lowestDto) {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }

    /**
      * Get the Data transfer object with this business entity's values
      *
      * @return a Data transfer object based upon this entity
      */
    @Override
    public com.splwg.cm.domain.wp.entity.CmFtGlFxAccountingId_DTO getDTO() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }




    /**
    * Set this object's fields from its corresponding data transfer object.
    * Accept a generic DTO, cast to my specific type.  Useful for framework code.
    *
    * @param dto the data transfer object
    */
    @Override
    public void setDTO(DataTransferObject<com.splwg.cm.domain.wp.entity.CmFtGlFxAccountingId> dto) {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }

     /**
     * @see  com.splwg.base.api.PersistentEntity#delete()
     */
    public void delete() {
        throw new UnsupportedOperationException("This method should be overridden by generated persistence code");    
    }


}
