/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: HibernatePOJOClass.vm
 * $File: //FW/2.0.5/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/HibernatePOJOClass.vm $
 * $DateTime: 2005/06/27 09:37:49 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.entity; 

import com.splwg.base.api.datatypes.Date;
import com.splwg.base.api.datatypes.Money;
import com.splwg.base.support.api.HibernatePOJOLookup;


import java.math.BigInteger;

public class CmFtGlAslAccountingId_POJO
{
    /* the prime key */
    private com.splwg.cm.domain.wp.entity.CmFtGlAslAccountingId_POJO_Id id;
    /* simple persistent fields */
    private String glAccount;
    private Date accountingDate;
    private String counterparty;
    private String businessUnit;
    private String costCenter;
    private String intercompany;
    private String scheme;
    private HibernatePOJOLookup financialTransactionType;
    private String batchControl;
    private BigInteger batchNumber;
    private String accountNumber;
    private Money amount;
    /* FK properties */
    /* optional FK properties */
    private com.splwg.base.domain.common.currency.Currency_POJO_Id currencyId;


    //~ Methods ------------------------------------------------------------------------------------------

    /* the prime key */
    public com.splwg.cm.domain.wp.entity.CmFtGlAslAccountingId_POJO_Id getId() {
        return id;
    }
    
    public void setId(com.splwg.cm.domain.wp.entity.CmFtGlAslAccountingId_POJO_Id newId) {
        this.id = newId;
    }

    /* simple persistent fields */
    public String getGlAccount() {
        return glAccount;
    }
    
    public void setGlAccount(String value) {
        this.glAccount = value;
    }

    public Date getAccountingDate() {
        return accountingDate;
    }
    
    public void setAccountingDate(Date value) {
        this.accountingDate = value;
    }

    public String getCounterparty() {
        return counterparty;
    }
    
    public void setCounterparty(String value) {
        this.counterparty = value;
    }

    public String getBusinessUnit() {
        return businessUnit;
    }
    
    public void setBusinessUnit(String value) {
        this.businessUnit = value;
    }

    public String getCostCenter() {
        return costCenter;
    }
    
    public void setCostCenter(String value) {
        this.costCenter = value;
    }

    public String getIntercompany() {
        return intercompany;
    }
    
    public void setIntercompany(String value) {
        this.intercompany = value;
    }

    public String getScheme() {
        return scheme;
    }
    
    public void setScheme(String value) {
        this.scheme = value;
    }

    public HibernatePOJOLookup getFinancialTransactionType() {
        return financialTransactionType;
    }
    
    public void setFinancialTransactionType(HibernatePOJOLookup value) {
        this.financialTransactionType = value;
    }

    public String getBatchControl() {
        return batchControl;
    }
    
    public void setBatchControl(String value) {
        this.batchControl = value;
    }

    public BigInteger getBatchNumber() {
        return batchNumber;
    }
    
    public void setBatchNumber(BigInteger value) {
        this.batchNumber = value;
    }

    public String getAccountNumber() {
        return accountNumber;
    }
    
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    public Money getAmount() {
        return amount;
    }
    
    public void setAmount(Money value) {
        this.amount = value;
    }


    /* FK properties */

    /* optional FK properties */

    /* Methods and properties for currencyId */

    public com.splwg.base.domain.common.currency.Currency_POJO_Id getCurrencyId() {
        return currencyId;
    }

    public void setCurrencyId(com.splwg.base.domain.common.currency.Currency_POJO_Id newId) {
        this.currencyId = newId;
    }


    public long version;
    public long getVersion() { return version; }
    public void setVersion(long newVersion) { version = newVersion; }
   
    @Override
    public String toString() {
        return "Entity: " + id.toString();
    }
}
