/**
 * Generated by com.splwg.tools.artifactgen.ArtifactGenerator
 * Template: HibernatePOJOClass.vm
 * $File: //FW/2.0.5/Code/modules/tools/source/java/com/splwg/tools/artifactgen/templates/HibernatePOJOClass.vm $
 * $DateTime: 2005/06/27 09:37:49 $
 * $Revision: #1 $
 */
package com.splwg.cm.domain.wp.entity; 

import com.splwg.base.api.datatypes.Date;


import java.math.BigInteger;

public class CmFtGlFxAccountingId_POJO
{
    /* the prime key */
    private com.splwg.cm.domain.wp.entity.CmFtGlFxAccountingId_POJO_Id id;
    /* simple persistent fields */
    private String glAccount;
    private Date accountingDate;
    private String fundCurrency;
    private String binSettlementCurrency;
    private String counterparty;
    private String businessUnit;
    private String batchControl;
    private BigInteger batchNumber;
    /* FK properties */
    /* optional FK properties */


    //~ Methods ------------------------------------------------------------------------------------------

    /* the prime key */
    public com.splwg.cm.domain.wp.entity.CmFtGlFxAccountingId_POJO_Id getId() {
        return id;
    }
    
    public void setId(com.splwg.cm.domain.wp.entity.CmFtGlFxAccountingId_POJO_Id newId) {
        this.id = newId;
    }

    /* simple persistent fields */
    public String getGlAccount() {
        return glAccount;
    }
    
    public void setGlAccount(String value) {
        this.glAccount = value;
    }

    public Date getAccountingDate() {
        return accountingDate;
    }
    
    public void setAccountingDate(Date value) {
        this.accountingDate = value;
    }

    public String getFundCurrency() {
        return fundCurrency;
    }
    
    public void setFundCurrency(String value) {
        this.fundCurrency = value;
    }

    public String getBinSettlementCurrency() {
        return binSettlementCurrency;
    }
    
    public void setBinSettlementCurrency(String value) {
        this.binSettlementCurrency = value;
    }

    public String getCounterparty() {
        return counterparty;
    }
    
    public void setCounterparty(String value) {
        this.counterparty = value;
    }

    public String getBusinessUnit() {
        return businessUnit;
    }
    
    public void setBusinessUnit(String value) {
        this.businessUnit = value;
    }

    public String getBatchControl() {
        return batchControl;
    }
    
    public void setBatchControl(String value) {
        this.batchControl = value;
    }

    public BigInteger getBatchNumber() {
        return batchNumber;
    }
    
    public void setBatchNumber(BigInteger value) {
        this.batchNumber = value;
    }


    /* FK properties */

    /* optional FK properties */


    public long version;
    public long getVersion() { return version; }
    public void setVersion(long newVersion) { version = newVersion; }
   
    @Override
    public String toString() {
        return "Entity: " + id.toString();
    }
}
